// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeSessionManager.Core.Data;

#nullable disable

namespace VeSessionManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729115123_CandidateLicenseClasses")]
    partial class CandidateLicenseClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApplicationDateEnteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRegisteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DayBeforeReminderSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsApplicantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FelonyDisclosureInstructionsSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FrnMissingAtRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasFelonyDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InitialLicenseClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LicenseGrantDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewLicenseClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PiiPurgedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationConfirmationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultMarkedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResultMarkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tested")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnmatchedReviewFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("YouthProgramInstructionsSentUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultMarkedByUserId");

                    b.HasIndex("SessionId", "ExamToolsApplicantId")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotificationEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivacyPolicyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TeamId", "Key")
                        .IsUnique();

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExamFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeeCollectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RetainedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("YouthExamFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VecId");

                    b.ToTable("FeeConfigurations");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.JobRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("JobRunHistories");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AmountMismatchFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpiredUnpaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentLinkUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentReminderSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefundNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefundRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RefundRequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefundRequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SquareAmountPaidUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareIdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SquareLinkPurgedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SquareOrderCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentLinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("YouthConfirmationToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RefundRequestedByUserId");

                    b.HasIndex("YouthConfirmationToken")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExamToolsSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RescheduleFlaggedForReview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RescheduleFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestingCompletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TestingCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VecSubmissionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VecSubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VecSubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ZoomDiscordSyncedStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomJoinUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomMeetingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamToolsSessionId")
                        .IsUnique();

                    b.HasIndex("FeeConfigurationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TestingCompletedByUserId");

                    b.HasIndex("VecId");

                    b.HasIndex("VecSubmittedByUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "VolunteerExaminerId");

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccDailyWatcherIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccDailyWatcherStartHourEt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccWeeklyCatchupDayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccWeeklyCatchupIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PiiRetentionWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionIngestionIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TestModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestModeOverrideEmail")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DiscordGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExamToolsBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsTeamCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIngestionRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurgeUnpaidLinkDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SmtpUseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareWebhookNotificationUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareWebhookSignatureKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoomBreakoutRoomCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<string>("ZoomClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UnmatchedSquarePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchedPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchedPaymentId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("TeamId", "SquareOrderId")
                        .IsUnique();

                    b.ToTable("UnmatchedSquarePayments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UserTeam", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsYouthProgram")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vecs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CallSign")
                        .IsUnique();

                    b.ToTable("VolunteerExaminers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ResultMarkedByUser")
                        .WithMany()
                        .HasForeignKey("ResultMarkedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("Candidates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultMarkedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailSettings", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("FeeConfigurations")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vec");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.JobRunHistory", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Candidate", "Candidate")
                        .WithMany("Payments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "RefundRequestedByUser")
                        .WithMany()
                        .HasForeignKey("RefundRequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Candidate");

                    b.Navigation("RefundRequestedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.FeeConfiguration", "FeeConfiguration")
                        .WithMany("Sessions")
                        .HasForeignKey("FeeConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany("Sessions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "TestingCompletedByUser")
                        .WithMany()
                        .HasForeignKey("TestingCompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("Sessions")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "VecSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("VecSubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeeConfiguration");

                    b.Navigation("Team");

                    b.Navigation("TestingCompletedByUser");

                    b.Navigation("Vec");

                    b.Navigation("VecSubmittedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SystemSettings", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UnmatchedSquarePayment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Payment", "MatchedPayment")
                        .WithMany()
                        .HasForeignKey("MatchedPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchedPayment");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ManagedByUser")
                        .WithMany()
                        .HasForeignKey("ManagedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UserTeam", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Team", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Navigation("FeeConfigurations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Navigation("SessionVolunteerExaminers");
                });
#pragma warning restore 612, 618
        }
    }
}
