// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeSessionManager.Core.Data;

#nullable disable

namespace VeSessionManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810032658_VeTagColor")]
    partial class VeTagColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApplicationDateEnteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRegisteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DayBeforeReminderSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsApplicantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FccHoldReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FccPaymentStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FccUlsLicenseKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FelonyDisclosureInstructionsSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FrnMissingAtRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasFelonyDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InitialLicenseClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LicenseGrantDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NewLicenseClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PiiPurgedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationConfirmationSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultMarkedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResultMarkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UlsApplicationFileNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnmatchedReviewFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("YouthProgramInstructionsSentUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultMarkedByUserId");

                    b.HasIndex("SessionId", "ExamToolsApplicantId")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminNotificationEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivacyPolicyUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("EmailSettings");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("TeamId", "Key")
                        .IsUnique();

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExamFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeeCollectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RetainedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("YouthExamFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VecId");

                    b.ToTable("FeeConfigurations");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.HistoricalImportRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CandidatesImported")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunksCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChunksTotal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionsImported")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("TeamId");

                    b.HasIndex("Status", "RequestedUtc");

                    b.ToTable("HistoricalImportRequests");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.JobRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("JobRunHistories");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AmountMismatchFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpiredUnpaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentLinkUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentReminderSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefundNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefundRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RefundRequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefundRequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SquareAmountPaidUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareIdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SquareLinkPurgedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SquareOrderCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentLinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("YouthConfirmationToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RefundRequestedByUserId");

                    b.HasIndex("YouthConfirmationToken")
                        .IsUnique();

                    b.HasIndex("CandidateId", "Reason")
                        .IsUnique()
                        .HasFilter("\"Reason\" = 0");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExamToolsClosedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RescheduleFlaggedForReview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RescheduleFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RetainedAmountOverride")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetainedAmountOverrideByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RetainedAmountOverrideUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestingCompletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TestingCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VeRosterFinalSyncedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VecSubmissionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VecSubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VecSubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ZoomDiscordSyncedStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomJoinUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomMeetingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamToolsSessionId")
                        .IsUnique();

                    b.HasIndex("FeeConfigurationId");

                    b.HasIndex("RetainedAmountOverrideByUserId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TestingCompletedByUserId");

                    b.HasIndex("VecId");

                    b.HasIndex("VecSubmittedByUserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "VolunteerExaminerId");

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PiiRetentionWindowDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionIngestionIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemSmtpFromAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemSmtpFromDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemSmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemSmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SystemSmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SystemSmtpUseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SystemSmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TestModeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestModeOverrideEmail")
                        .HasColumnType("TEXT");

                    b.Property<int>("UlsWatcherIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UlsWatcherStartHourEt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("DiscordGuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExamToolsBaseUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsTeamCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastIngestionRunUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("BLOB");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LogoUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurgeUnpaidLinkDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(30);

                    b.Property<string>("SmtpHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SmtpUseStartTls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareAccessToken")
                        .HasColumnType("TEXT");

                    b.Property<int>("SquareEnvironment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("SquareLocationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareWebhookNotificationUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareWebhookSignatureKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoomBreakoutRoomCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(2);

                    b.Property<string>("ZoomClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UnmatchedSquarePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountUsd")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("BuyerEmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchedPaymentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquareOrderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MatchedPaymentId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("TeamId", "SquareOrderId")
                        .IsUnique();

                    b.ToTable("UnmatchedSquarePayments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPasswordResetRequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UserTeam", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeCallSignHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReplacedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CallSign");

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("VeCallSignHistories");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeEmailChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfirmationSentToEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ConfirmedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("VeEmailChangeRequests");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeSelfServiceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ConsumedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SentToEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("VeSelfServiceTokens");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique();

                    b.ToTable("VeTags");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTagAssignment", b =>
                {
                    b.Property<int>("VeTeamMembershipId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VeTagId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("VeTeamMembershipId", "VeTagId");

                    b.HasIndex("VeTagId");

                    b.ToTable("VeTagAssignments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTeamMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InactivatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("VolunteerExaminerId", "TeamId")
                        .IsUnique();

                    b.ToTable("VeTeamMemberships");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeVecAccreditation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VecId");

                    b.HasIndex("VolunteerExaminerId", "VecId")
                        .IsUnique();

                    b.ToTable("VeVecAccreditations");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExamToolsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsYouthProgram")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamToolsCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Vecs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConflictingFrn")
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactPreference")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseCancellationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseGrantDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LicenseLastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LicenseNotFoundAtFcc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicenseStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MergedIntoVolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CallSign");

                    b.HasIndex("Frn")
                        .IsUnique()
                        .HasFilter("\"Frn\" IS NOT NULL");

                    b.HasIndex("MergedIntoVolunteerExaminerId");

                    b.ToTable("VolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.WatchedLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancellationDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiredDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiredDateWhenRenewalFiledUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GrantDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastCheckedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseeName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotFoundAtFcc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorClass")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RenewalConfirmedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenewalFileNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RenewalPendingSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("LastCheckedUtc");

                    b.HasIndex("TeamId", "CallSign")
                        .IsUnique();

                    b.ToTable("WatchedLicenses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ResultMarkedByUser")
                        .WithMany()
                        .HasForeignKey("ResultMarkedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("Candidates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultMarkedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailSettings", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("FeeConfigurations")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vec");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.HistoricalImportRequest", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.JobRunHistory", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Candidate", "Candidate")
                        .WithMany("Payments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "RefundRequestedByUser")
                        .WithMany()
                        .HasForeignKey("RefundRequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Candidate");

                    b.Navigation("RefundRequestedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.FeeConfiguration", "FeeConfiguration")
                        .WithMany("Sessions")
                        .HasForeignKey("FeeConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "RetainedAmountOverrideByUser")
                        .WithMany()
                        .HasForeignKey("RetainedAmountOverrideByUserId");

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany("Sessions")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "TestingCompletedByUser")
                        .WithMany()
                        .HasForeignKey("TestingCompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("Sessions")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "VecSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("VecSubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeeConfiguration");

                    b.Navigation("RetainedAmountOverrideByUser");

                    b.Navigation("Team");

                    b.Navigation("TestingCompletedByUser");

                    b.Navigation("Vec");

                    b.Navigation("VecSubmittedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SystemSettings", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UnmatchedSquarePayment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Payment", "MatchedPayment")
                        .WithMany()
                        .HasForeignKey("MatchedPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MatchedPayment");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ManagedByUser")
                        .WithMany()
                        .HasForeignKey("ManagedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.UserTeam", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeCallSignHistory", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("CallSignHistory")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeEmailChangeRequest", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany()
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeSelfServiceToken", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany()
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTag", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTagAssignment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.VeTag", "VeTag")
                        .WithMany("Assignments")
                        .HasForeignKey("VeTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VeTeamMembership", "VeTeamMembership")
                        .WithMany("TagAssignments")
                        .HasForeignKey("VeTeamMembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VeTag");

                    b.Navigation("VeTeamMembership");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTeamMembership", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeVecAccreditation", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany()
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("VecAccreditations")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vec");

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "MergedIntoVolunteerExaminer")
                        .WithMany()
                        .HasForeignKey("MergedIntoVolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MergedIntoVolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.WatchedLicense", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "AddedByUser")
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Team", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTag", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VeTeamMembership", b =>
                {
                    b.Navigation("TagAssignments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Navigation("FeeConfigurations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Navigation("CallSignHistory");

                    b.Navigation("SessionVolunteerExaminers");

                    b.Navigation("TeamMemberships");

                    b.Navigation("VecAccreditations");
                });
#pragma warning restore 612, 618
        }
    }
}
