// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeSessionManager.Core.Data;

#nullable disable

namespace VeSessionManager.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716050402_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApplicationDateEnteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRegisteredUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FrnMissingAtRegistration")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasFelonyDisclosure")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LicenseGrantDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PiiPurgedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultMarkedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResultMarkedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tested")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResultMarkedByUserId");

                    b.HasIndex("SessionId");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExamFeeAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("FeeCollectionEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RetainedAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("VecId");

                    b.ToTable("FeeConfigurations");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.JobRunHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JobRunHistories");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CandidateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExpiredUnpaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PaidDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentLinkUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentReminderSentUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefundNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefundRequested")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RefundRequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RefundRequestedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SquarePaymentReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId");

                    b.HasIndex("RefundRequestedByUserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArrlSubmissionStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArrlSubmittedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ArrlSubmittedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordEventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamToolsSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FeeConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RescheduleFlaggedForReview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RescheduleFlaggedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TestingCompletedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TestingCompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VecId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZoomJoinUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZoomMeetingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArrlSubmittedByUserId");

                    b.HasIndex("FeeConfigurationId");

                    b.HasIndex("TestingCompletedByUserId");

                    b.HasIndex("VecId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerExaminerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SessionId", "VolunteerExaminerId");

                    b.HasIndex("VolunteerExaminerId");

                    b.ToTable("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagedByUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsYouthProgram")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vecs");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallSign")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ResultMarkedByUser")
                        .WithMany()
                        .HasForeignKey("ResultMarkedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("Candidates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResultMarkedByUser");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.EmailTemplate", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("FeeConfigurations")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Vec");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Payment", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Candidate", "Candidate")
                        .WithMany("Payments")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "RefundRequestedByUser")
                        .WithMany()
                        .HasForeignKey("RefundRequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Candidate");

                    b.Navigation("RefundRequestedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ArrlSubmittedByUser")
                        .WithMany()
                        .HasForeignKey("ArrlSubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.FeeConfiguration", "FeeConfiguration")
                        .WithMany("Sessions")
                        .HasForeignKey("FeeConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.User", "TestingCompletedByUser")
                        .WithMany()
                        .HasForeignKey("TestingCompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VeSessionManager.Core.Entities.Vec", "Vec")
                        .WithMany("Sessions")
                        .HasForeignKey("VecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrlSubmittedByUser");

                    b.Navigation("FeeConfiguration");

                    b.Navigation("TestingCompletedByUser");

                    b.Navigation("Vec");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.SessionVolunteerExaminer", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.Session", "Session")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeSessionManager.Core.Entities.VolunteerExaminer", "VolunteerExaminer")
                        .WithMany("SessionVolunteerExaminers")
                        .HasForeignKey("VolunteerExaminerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("VolunteerExaminer");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.User", b =>
                {
                    b.HasOne("VeSessionManager.Core.Entities.User", "ManagedByUser")
                        .WithMany()
                        .HasForeignKey("ManagedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManagedByUser");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Candidate", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.FeeConfiguration", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Session", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("SessionVolunteerExaminers");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.Vec", b =>
                {
                    b.Navigation("FeeConfigurations");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VeSessionManager.Core.Entities.VolunteerExaminer", b =>
                {
                    b.Navigation("SessionVolunteerExaminers");
                });
#pragma warning restore 612, 618
        }
    }
}
